#!/bin/bash
g++ procesarDatos2.cpp
./a.out<t1 >>test1.csv
./a.out<t2 >>test1.csv
./a.out<t3 >>test1.csv
./a.out<t4 >>test1.csv
./a.out<t5 >>test1.csv
./a.out<t6 >>test1.csv
./a.out<t7 >>test1.csv
./a.out<t8 >>test1.csv
./a.out<t9 >>test1.csv
./a.out<t10 >>test1.csv
./a.out<t11 >>test1.csv
./a.out<t12 >>test1.csv
./a.out<t13 >>test1.csv
./a.out<t14 >>test1.csv
./a.out<t15 >>test1.csv

g++ procesarDatos3.cpp
./a.out<t1 >>test2.csv
./a.out<t2 >>test2.csv
./a.out<t3 >>test2.csv
./a.out<t4 >>test2.csv
./a.out<t5 >>test2.csv
./a.out<t6 >>test2.csv
./a.out<t7 >>test2.csv
./a.out<t8 >>test2.csv
./a.out<t9 >>test2.csv
./a.out<t10 >>test2.csv
./a.out<t11 >>test2.csv
./a.out<t12 >>test2.csv
./a.out<t13 >>test2.csv
./a.out<t14 >>test2.csv
./a.out<t15 >>test2.csv
